language: node_js

node_js:
  - 10

script:
#  - node ./internals/scripts/generate-templates-for-linting
#  - npm run test
#  - npm run build
  #- node_modules/.bin/jest build.test.js
  #- node_modules/.bin/jest content.test.js
  #- node_modules/.bin/jest harvest.test.js
  - node_modules/.bin/jest schema.test.js

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
